task: classification

model:
  name: NASNetMobile
  include_top: false
  fine_tune: false
  save_model: false

training:
  batch_size: 16
  epochs: 1
  learning_rate: 0.0001
  early_stopping_patience: 4

cross_validation: false
