task: classification

model:
  # name: NASNetMobile
  name: InceptionV3
  # name: ResNet101
  include_top: false
  fine_tune: true
  save_model: false
  use_l2_regularization: false
  l2_regularization: 1e-4
  use_dropout: false
  dropout: 0.25

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.01
  early_stopping_patience: 4
  reduce_lr_patience: 3

cross_validation: false
